/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IJBFundingCycleBallot,
  IJBFundingCycleBallotInterface,
} from "../IJBFundingCycleBallot";

const _abi = [
  {
    inputs: [],
    name: "duration",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_projectId",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_configuration",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_start",
        type: "uint256",
      },
    ],
    name: "stateOf",
    outputs: [
      {
        internalType: "enum JBBallotState",
        name: "",
        type: "uint8",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes4",
        name: "interfaceId",
        type: "bytes4",
      },
    ],
    name: "supportsInterface",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IJBFundingCycleBallot__factory {
  static readonly abi = _abi;
  static createInterface(): IJBFundingCycleBallotInterface {
    return new utils.Interface(_abi) as IJBFundingCycleBallotInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IJBFundingCycleBallot {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as IJBFundingCycleBallot;
  }
}
