/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { IJBMigratable, IJBMigratableInterface } from "../IJBMigratable";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_projectId",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "_from",
        type: "address",
      },
    ],
    name: "prepForMigrationOf",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IJBMigratable__factory {
  static readonly abi = _abi;
  static createInterface(): IJBMigratableInterface {
    return new utils.Interface(_abi) as IJBMigratableInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IJBMigratable {
    return new Contract(address, _abi, signerOrProvider) as IJBMigratable;
  }
}
