/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { IJBPriceFeed, IJBPriceFeedInterface } from "../IJBPriceFeed";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_targetDecimals",
        type: "uint256",
      },
    ],
    name: "currentPrice",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IJBPriceFeed__factory {
  static readonly abi = _abi;
  static createInterface(): IJBPriceFeedInterface {
    return new utils.Interface(_abi) as IJBPriceFeedInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IJBPriceFeed {
    return new Contract(address, _abi, signerOrProvider) as IJBPriceFeed;
  }
}
