/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IJBPaymentTerminalUtility,
  IJBPaymentTerminalUtilityInterface,
} from "../IJBPaymentTerminalUtility";

const _abi = [
  {
    inputs: [],
    name: "directory",
    outputs: [
      {
        internalType: "contract IJBDirectory",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IJBPaymentTerminalUtility__factory {
  static readonly abi = _abi;
  static createInterface(): IJBPaymentTerminalUtilityInterface {
    return new utils.Interface(_abi) as IJBPaymentTerminalUtilityInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IJBPaymentTerminalUtility {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as IJBPaymentTerminalUtility;
  }
}
