/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  JBControllerUtility,
  JBControllerUtilityInterface,
} from "../JBControllerUtility";

const _abi = [
  {
    inputs: [],
    name: "CONTROLLER_UNAUTHORIZED",
    type: "error",
  },
  {
    inputs: [],
    name: "directory",
    outputs: [
      {
        internalType: "contract IJBDirectory",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class JBControllerUtility__factory {
  static readonly abi = _abi;
  static createInterface(): JBControllerUtilityInterface {
    return new utils.Interface(_abi) as JBControllerUtilityInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): JBControllerUtility {
    return new Contract(address, _abi, signerOrProvider) as JBControllerUtility;
  }
}
