/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type { JBCurrencies, JBCurrenciesInterface } from "../JBCurrencies";

const _abi = [
  {
    inputs: [],
    name: "ETH",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "USD",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

const _bytecode =
  "0x6098610038600b82828239805160001a607314602b57634e487b7160e01b600052600060045260246000fd5b30600052607381538281f3fe7300000000000000000000000000000000000000003014608060405260043610603d5760003560e01c80631bf6c21b1460425780638322fff214605b575b600080fd5b6049600281565b60405190815260200160405180910390f35b604960018156fea2646970667358221220093e544418be142e736151eaaee2d2eaaadd98871336455faf264e2b9a92088764736f6c634300080d0033";

type JBCurrenciesConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: JBCurrenciesConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class JBCurrencies__factory extends ContractFactory {
  constructor(...args: JBCurrenciesConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
    this.contractName = "JBCurrencies";
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<JBCurrencies> {
    return super.deploy(overrides || {}) as Promise<JBCurrencies>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): JBCurrencies {
    return super.attach(address) as JBCurrencies;
  }
  connect(signer: Signer): JBCurrencies__factory {
    return super.connect(signer) as JBCurrencies__factory;
  }
  static readonly contractName: "JBCurrencies";
  public readonly contractName: "JBCurrencies";
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): JBCurrenciesInterface {
    return new utils.Interface(_abi) as JBCurrenciesInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): JBCurrencies {
    return new Contract(address, _abi, signerOrProvider) as JBCurrencies;
  }
}
