/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type { JBOperations, JBOperationsInterface } from "../JBOperations";

const _abi = [
  {
    inputs: [],
    name: "BURN",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "CHANGE_TOKEN",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "CLAIM",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "ISSUE",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "MIGRATE_CONTROLLER",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "MIGRATE_TERMINAL",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "MINT",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "PROCESS_FEES",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "RECONFIGURE",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "REDEEM",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "REQUIRE_CLAIM",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "SET_CONTROLLER",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "SET_METADATA",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "SET_PRIMARY_TERMINAL",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "SET_SPLITS",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "SET_TERMINALS",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "TRANSFER",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "USE_ALLOWANCE",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

const _bytecode =
  "0x6101fd61003a600b82828239805160001a60731461002d57634e487b7160e01b600052600060045260246000fd5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600436106101205760003560e01c80639694c99a116100ac578063b56dcf9e1161007b578063b56dcf9e1461019f578063c0a2526c146101a7578063c577af30146101af578063ef1b4f3b146101b7578063f5edee14146101bf57600080fd5b80639694c99a1461017f578063a264ed7814610187578063aae781031461018f578063af0c22a01461019757600080fd5b80636fe7cac6116100f35780636fe7cac61461015757806373b6dec61461015f57806373d7487614610167578063757616e11461016f57806376420e1d1461017757600080fd5b80631d4b9a431461012557806332235cdf1461013f5780633e36f4c7146101475780636c1943be1461014f575b600080fd5b61012d600181565b60405190815260200160405180910390f35b61012d600781565b61012d600981565b61012d600f81565b61012d600881565b61012d601181565b61012d600b81565b61012d600d81565b61012d600c81565b61012d600581565b61012d600381565b61012d601081565b61012d600681565b61012d600481565b61012d600a81565b61012d600281565b61012d601281565b61012d600e8156fea2646970667358221220e20e19eb5c5ac96a5942ae105ae8b9e1b3374b28d45677fa502b99f13889afe664736f6c634300080d0033";

type JBOperationsConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: JBOperationsConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class JBOperations__factory extends ContractFactory {
  constructor(...args: JBOperationsConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
    this.contractName = "JBOperations";
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<JBOperations> {
    return super.deploy(overrides || {}) as Promise<JBOperations>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): JBOperations {
    return super.attach(address) as JBOperations;
  }
  connect(signer: Signer): JBOperations__factory {
    return super.connect(signer) as JBOperations__factory;
  }
  static readonly contractName: "JBOperations";
  public readonly contractName: "JBOperations";
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): JBOperationsInterface {
    return new utils.Interface(_abi) as JBOperationsInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): JBOperations {
    return new Contract(address, _abi, signerOrProvider) as JBOperations;
  }
}
