/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result, EventFragment } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface IJBETHERC20SplitsPayerDeployerInterface
  extends utils.Interface {
  contractName: "IJBETHERC20SplitsPayerDeployer";
  functions: {
    "deploySplitsPayer(uint256,uint256,uint256,address,uint256,address,bool,string,bytes,bool,address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "deploySplitsPayer",
    values: [
      BigNumberish,
      BigNumberish,
      BigNumberish,
      string,
      BigNumberish,
      string,
      boolean,
      string,
      BytesLike,
      boolean,
      string
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "deploySplitsPayer",
    data: BytesLike
  ): Result;

  events: {
    "DeploySplitsPayer(address,uint256,uint256,uint256,address,uint256,address,bool,string,bytes,bool,address,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "DeploySplitsPayer"): EventFragment;
}

export type DeploySplitsPayerEvent = TypedEvent<
  [
    string,
    BigNumber,
    BigNumber,
    BigNumber,
    string,
    BigNumber,
    string,
    boolean,
    string,
    string,
    boolean,
    string,
    string
  ],
  {
    splitsPayer: string;
    defaultSplitsProjectId: BigNumber;
    defaultSplitsDomain: BigNumber;
    defaultSplitsGroup: BigNumber;
    splitsStore: string;
    defaultProjectId: BigNumber;
    defaultBeneficiary: string;
    defaultPreferClaimedTokens: boolean;
    defaultMemo: string;
    defaultMetadata: string;
    preferAddToBalance: boolean;
    owner: string;
    caller: string;
  }
>;

export type DeploySplitsPayerEventFilter =
  TypedEventFilter<DeploySplitsPayerEvent>;

export interface IJBETHERC20SplitsPayerDeployer extends BaseContract {
  contractName: "IJBETHERC20SplitsPayerDeployer";
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IJBETHERC20SplitsPayerDeployerInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    deploySplitsPayer(
      _defaultSplitsProjectId: BigNumberish,
      _defaultSplitsDomain: BigNumberish,
      _defaultSplitsGroup: BigNumberish,
      _splitsStore: string,
      _defaultProjectId: BigNumberish,
      _defaultBeneficiary: string,
      _defaultPreferClaimedTokens: boolean,
      _defaultMemo: string,
      _defaultMetadata: BytesLike,
      _preferAddToBalance: boolean,
      _owner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  deploySplitsPayer(
    _defaultSplitsProjectId: BigNumberish,
    _defaultSplitsDomain: BigNumberish,
    _defaultSplitsGroup: BigNumberish,
    _splitsStore: string,
    _defaultProjectId: BigNumberish,
    _defaultBeneficiary: string,
    _defaultPreferClaimedTokens: boolean,
    _defaultMemo: string,
    _defaultMetadata: BytesLike,
    _preferAddToBalance: boolean,
    _owner: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    deploySplitsPayer(
      _defaultSplitsProjectId: BigNumberish,
      _defaultSplitsDomain: BigNumberish,
      _defaultSplitsGroup: BigNumberish,
      _splitsStore: string,
      _defaultProjectId: BigNumberish,
      _defaultBeneficiary: string,
      _defaultPreferClaimedTokens: boolean,
      _defaultMemo: string,
      _defaultMetadata: BytesLike,
      _preferAddToBalance: boolean,
      _owner: string,
      overrides?: CallOverrides
    ): Promise<string>;
  };

  filters: {
    "DeploySplitsPayer(address,uint256,uint256,uint256,address,uint256,address,bool,string,bytes,bool,address,address)"(
      splitsPayer?: string | null,
      defaultSplitsProjectId?: null,
      defaultSplitsDomain?: null,
      defaultSplitsGroup?: null,
      splitsStore?: null,
      defaultProjectId?: null,
      defaultBeneficiary?: null,
      defaultPreferClaimedTokens?: null,
      defaultMemo?: null,
      defaultMetadata?: null,
      preferAddToBalance?: null,
      owner?: null,
      caller?: null
    ): DeploySplitsPayerEventFilter;
    DeploySplitsPayer(
      splitsPayer?: string | null,
      defaultSplitsProjectId?: null,
      defaultSplitsDomain?: null,
      defaultSplitsGroup?: null,
      splitsStore?: null,
      defaultProjectId?: null,
      defaultBeneficiary?: null,
      defaultPreferClaimedTokens?: null,
      defaultMemo?: null,
      defaultMetadata?: null,
      preferAddToBalance?: null,
      owner?: null,
      caller?: null
    ): DeploySplitsPayerEventFilter;
  };

  estimateGas: {
    deploySplitsPayer(
      _defaultSplitsProjectId: BigNumberish,
      _defaultSplitsDomain: BigNumberish,
      _defaultSplitsGroup: BigNumberish,
      _splitsStore: string,
      _defaultProjectId: BigNumberish,
      _defaultBeneficiary: string,
      _defaultPreferClaimedTokens: boolean,
      _defaultMemo: string,
      _defaultMetadata: BytesLike,
      _preferAddToBalance: boolean,
      _owner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    deploySplitsPayer(
      _defaultSplitsProjectId: BigNumberish,
      _defaultSplitsDomain: BigNumberish,
      _defaultSplitsGroup: BigNumberish,
      _splitsStore: string,
      _defaultProjectId: BigNumberish,
      _defaultBeneficiary: string,
      _defaultPreferClaimedTokens: boolean,
      _defaultMemo: string,
      _defaultMetadata: BytesLike,
      _preferAddToBalance: boolean,
      _owner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
