/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface JBConstantsInterface extends utils.Interface {
  contractName: "JBConstants";
  functions: {
    "MAX_DISCOUNT_RATE()": FunctionFragment;
    "MAX_FEE()": FunctionFragment;
    "MAX_FEE_DISCOUNT()": FunctionFragment;
    "MAX_REDEMPTION_RATE()": FunctionFragment;
    "MAX_RESERVED_RATE()": FunctionFragment;
    "SPLITS_TOTAL_PERCENT()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "MAX_DISCOUNT_RATE",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "MAX_FEE", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "MAX_FEE_DISCOUNT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_REDEMPTION_RATE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_RESERVED_RATE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "SPLITS_TOTAL_PERCENT",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "MAX_DISCOUNT_RATE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "MAX_FEE", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "MAX_FEE_DISCOUNT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_REDEMPTION_RATE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_RESERVED_RATE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "SPLITS_TOTAL_PERCENT",
    data: BytesLike
  ): Result;

  events: {};
}

export interface JBConstants extends BaseContract {
  contractName: "JBConstants";
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: JBConstantsInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    MAX_DISCOUNT_RATE(overrides?: CallOverrides): Promise<[BigNumber]>;

    MAX_FEE(overrides?: CallOverrides): Promise<[BigNumber]>;

    MAX_FEE_DISCOUNT(overrides?: CallOverrides): Promise<[BigNumber]>;

    MAX_REDEMPTION_RATE(overrides?: CallOverrides): Promise<[BigNumber]>;

    MAX_RESERVED_RATE(overrides?: CallOverrides): Promise<[BigNumber]>;

    SPLITS_TOTAL_PERCENT(overrides?: CallOverrides): Promise<[BigNumber]>;
  };

  MAX_DISCOUNT_RATE(overrides?: CallOverrides): Promise<BigNumber>;

  MAX_FEE(overrides?: CallOverrides): Promise<BigNumber>;

  MAX_FEE_DISCOUNT(overrides?: CallOverrides): Promise<BigNumber>;

  MAX_REDEMPTION_RATE(overrides?: CallOverrides): Promise<BigNumber>;

  MAX_RESERVED_RATE(overrides?: CallOverrides): Promise<BigNumber>;

  SPLITS_TOTAL_PERCENT(overrides?: CallOverrides): Promise<BigNumber>;

  callStatic: {
    MAX_DISCOUNT_RATE(overrides?: CallOverrides): Promise<BigNumber>;

    MAX_FEE(overrides?: CallOverrides): Promise<BigNumber>;

    MAX_FEE_DISCOUNT(overrides?: CallOverrides): Promise<BigNumber>;

    MAX_REDEMPTION_RATE(overrides?: CallOverrides): Promise<BigNumber>;

    MAX_RESERVED_RATE(overrides?: CallOverrides): Promise<BigNumber>;

    SPLITS_TOTAL_PERCENT(overrides?: CallOverrides): Promise<BigNumber>;
  };

  filters: {};

  estimateGas: {
    MAX_DISCOUNT_RATE(overrides?: CallOverrides): Promise<BigNumber>;

    MAX_FEE(overrides?: CallOverrides): Promise<BigNumber>;

    MAX_FEE_DISCOUNT(overrides?: CallOverrides): Promise<BigNumber>;

    MAX_REDEMPTION_RATE(overrides?: CallOverrides): Promise<BigNumber>;

    MAX_RESERVED_RATE(overrides?: CallOverrides): Promise<BigNumber>;

    SPLITS_TOTAL_PERCENT(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    MAX_DISCOUNT_RATE(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    MAX_FEE(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    MAX_FEE_DISCOUNT(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    MAX_REDEMPTION_RATE(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    MAX_RESERVED_RATE(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    SPLITS_TOTAL_PERCENT(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
